export function getExtensionsList() {
  return [
    { Emp_Name: 'Syed Salman Hussain', Dept_Descr: 'Management', DSG_Descr: 'CEO', CT_Descr: 'Karachi', TEL_EXT: '111' },
    { Emp_Name: 'Ubaid Ullah', Dept_Descr: 'Administration', DSG_Descr: 'Manager  Admin', CT_Descr: 'Karachi', TEL_EXT: '200' },
    { Emp_Name: 'Furqan', Dept_Descr: 'Administration', DSG_Descr: 'Supervisor, Admin', CT_Descr: 'Karachi', TEL_EXT: '201' },
    { Emp_Name: 'Humna Altamash Yousuf', Dept_Descr: 'Human Resource', DSG_Descr: 'Manager HR & Organization Development', CT_Descr: 'Karachi', TEL_EXT: '403' },
    { Emp_Name: 'Muhammad Fahad', Dept_Descr: 'Accounts & Finance', DSG_Descr: 'Head - Accounts & Finance', CT_Descr: 'Karachi', TEL_EXT: '301' },
    { Emp_Name: 'Vivian Charles Paul', Dept_Descr: 'Corporate Services', DSG_Descr: 'Head - Corporate Services & Renewal', CT_Descr: 'Karachi', TEL_EXT: '203' },
    { Emp_Name: 'Sidra Tiwana', Dept_Descr: 'Corporate Services', DSG_Descr: 'Deputy Manager, Corporate Services', CT_Descr: 'Karachi', TEL_EXT: '204' },
    { Emp_Name: 'Syed Zia Abid Naqvi', Dept_Descr: 'Control Room', DSG_Descr: 'Head - Control Center', CT_Descr: 'Karachi', TEL_EXT: '110' },
    { Emp_Name: 'Sobia Ali', Dept_Descr: 'Diagnostics & Harness', DSG_Descr: 'Head - Technical Diagnostics', CT_Descr: 'Karachi', TEL_EXT: '802' },
    { Emp_Name: 'Joseph Henry', Dept_Descr: 'Control Room', DSG_Descr: 'Assistant Manager, CR', CT_Descr: 'Karachi', TEL_EXT: '457' },
    { Emp_Name: 'Anil', Dept_Descr: 'Control Room', DSG_Descr: 'Assistant Manager, CR', CT_Descr: 'Karachi', TEL_EXT: '453' },
    { Emp_Name: 'Muhammad Shakir', Dept_Descr: 'Control Room', DSG_Descr: 'Supervisor, CR', CT_Descr: 'Karachi', TEL_EXT: '458' },
    { Emp_Name: 'Rahat Gul', Dept_Descr: 'Removal Department', DSG_Descr: 'Supervisor, Removal', CT_Descr: 'Karachi', TEL_EXT: '480' },
    { Emp_Name: 'Syed Asad Raza', Dept_Descr: 'Control Room', DSG_Descr: 'Supervisor, CR', CT_Descr: 'Karachi', TEL_EXT: '458' },
    { Emp_Name: 'Tariq Shahzad', Dept_Descr: 'Sales & Marketing', DSG_Descr: 'Head (Nation Wide) - Sales & Marketing', CT_Descr: 'Karachi', TEL_EXT: '706' },
    { Emp_Name: 'Muhammad Umer Azeem', Dept_Descr: 'Sales & Marketing', DSG_Descr: 'Assistant Manager, Sales & Marketing ', CT_Descr: 'Karachi', TEL_EXT: '558' },
    { Emp_Name: 'Hassan Mustafa', Dept_Descr: 'Sales & Marketing', DSG_Descr: 'Assistant Manager, Sales & Marketing ', CT_Descr: 'Karachi', TEL_EXT: '474' },
    { Emp_Name: 'Farhana Faisal', Dept_Descr: 'Sales & Marketing', DSG_Descr: 'BDO', CT_Descr: 'Karachi', TEL_EXT: '703' },
    { Emp_Name: 'Afser Ali Khan', Dept_Descr: 'Inventory & Procurement', DSG_Descr: 'Assistant Manager, Inventory', CT_Descr: 'Karachi', TEL_EXT: '202' },
    { Emp_Name: 'Mairaj-ul-Haq', Dept_Descr: 'Sales & Marketing', DSG_Descr: 'Sales Coordinator', CT_Descr: 'Karachi', TEL_EXT: '713' },
    { Emp_Name: 'Muhammad Jawad Ali Khan', Dept_Descr: 'Diagnostics & Harness', DSG_Descr: 'Assistant Manager, Diagnostics', CT_Descr: 'Karachi', TEL_EXT: '814' },
    { Emp_Name: 'Muhammad Luqman Farooq ', Dept_Descr: 'Technical', DSG_Descr: 'Technician', CT_Descr: 'Lahore', TEL_EXT: '10067' },
    { Emp_Name: 'Fahad Ali Khan', Dept_Descr: 'Sales & Marketing', DSG_Descr: 'Regional Head (South) - Sales & Marketing ', CT_Descr: 'Karachi', TEL_EXT: '707' },
    { Emp_Name: 'Naveed Shahzad', Dept_Descr: 'Accounts & Finance', DSG_Descr: 'Deputy Manager, Accounts & Finance', CT_Descr: 'Karachi', TEL_EXT: '303' },
    { Emp_Name: 'Muhammad Asif', Dept_Descr: 'Inventory & Procurement', DSG_Descr: 'Head - Inventory & Procurement ', CT_Descr: 'Karachi', TEL_EXT: '809' },
    { Emp_Name: 'Muhammad Ejaz', Dept_Descr: 'Technical', DSG_Descr: 'Technician', CT_Descr: 'Dina', TEL_EXT: '472' },
    { Emp_Name: 'Syed Muhammad Hasnain', Dept_Descr: 'Removal Department', DSG_Descr: 'Removal Officer', CT_Descr: 'Karachi', TEL_EXT: '483' },
    { Emp_Name: 'Anas Kamil', Dept_Descr: 'Corporate Services', DSG_Descr: 'Customer Services Executive', CT_Descr: 'Karachi', TEL_EXT: '478' },
    { Emp_Name: 'Syed Adnan Mansoor', Dept_Descr: 'Marketing', DSG_Descr: 'Creative Specialist', CT_Descr: 'Karachi', TEL_EXT: '810' },
    { Emp_Name: 'Syed Muhammad Asad', Dept_Descr: 'Technical', DSG_Descr: 'Team Lead, Technical Coordinator', CT_Descr: 'Karachi', TEL_EXT: '804' },
    { Emp_Name: 'Adnan', Dept_Descr: 'Accounts & Finance', DSG_Descr: 'Rider', CT_Descr: 'Karachi', TEL_EXT: '202' },
    { Emp_Name: 'Muhammad Zakir', Dept_Descr: 'Information Technology', DSG_Descr: 'Manager, IT', CT_Descr: 'Karachi', TEL_EXT: '400' },
    { Emp_Name: 'Hasnain', Dept_Descr: 'Diagnostics & Harness', DSG_Descr: 'Supervisor ', CT_Descr: 'Karachi', TEL_EXT: '811' },
    { Emp_Name: 'Zohra Abbasi', Dept_Descr: 'Accounts & Finance', DSG_Descr: 'Executive, Accounts & Finance', CT_Descr: 'Karachi', TEL_EXT: '302' },
    { Emp_Name: 'Shahzor Domnic', Dept_Descr: 'Removal Department', DSG_Descr: 'Removal Officer', CT_Descr: 'Karachi', TEL_EXT: '475' },
    { Emp_Name: 'Muhammad Hamza Khan', Dept_Descr: 'Software Development', DSG_Descr: 'Software Engineer II', CT_Descr: 'Karachi', TEL_EXT: '704' },
    { Emp_Name: 'Muhammad Sheheryar Izhar', Dept_Descr: 'Software Development', DSG_Descr: 'Dot Net developer', CT_Descr: 'Karachi', TEL_EXT: '556' },
    { Emp_Name: 'Kamran Jamal Nasir', Dept_Descr: 'Software Development', DSG_Descr: 'ERP Manager', CT_Descr: 'Karachi', TEL_EXT: '556' },
    { Emp_Name: 'Syed Saboor Ali', Dept_Descr: 'Marketing', DSG_Descr: 'Team Lead, Digital Marketing', CT_Descr: 'Karachi', TEL_EXT: '712' },
    { Emp_Name: 'Muhammad Saif Malik', Dept_Descr: 'Removal Department', DSG_Descr: 'Removal Officer', CT_Descr: 'Karachi', TEL_EXT: '479' },
    { Emp_Name: 'Daiya Sagar', Dept_Descr: 'Human Resource', DSG_Descr: 'Sr. HR Officer', CT_Descr: 'Karachi', TEL_EXT: '404' },
    { Emp_Name: 'Danish Akbar', Dept_Descr: 'Accounts & Finance', DSG_Descr: 'Finance Officer', CT_Descr: 'Karachi', TEL_EXT: '228' },
    { Emp_Name: 'Syed Shabbir Hussain Naqvi', Dept_Descr: 'Security Department', DSG_Descr: 'Head of Security', CT_Descr: 'Karachi', TEL_EXT: '205' },
    { Emp_Name: 'Dawood Ahmed', Dept_Descr: 'Corporate Services', DSG_Descr: 'Supervisor Corporate Services ', CT_Descr: 'Karachi', TEL_EXT: '472' },
    { Emp_Name: 'Syed Muneeb Hussain', Dept_Descr: 'Marketing', DSG_Descr: 'Digital Sales Officer ', CT_Descr: 'Karachi', TEL_EXT: '708' },
    { Emp_Name: 'Muhammad Atif Khatri', Dept_Descr: 'Software Development', DSG_Descr: 'Software Engineer II', CT_Descr: 'Karachi', TEL_EXT: '801' },
    { Emp_Name: 'Muhammad Yaqoob', Dept_Descr: 'Corporate Services', DSG_Descr: 'NR Executive', CT_Descr: 'Karachi', TEL_EXT: '307' },
    { Emp_Name: 'Nadeem Qasim', Dept_Descr: 'Management', DSG_Descr: 'Personal Assistant', CT_Descr: 'Karachi', TEL_EXT: '101' },
    { Emp_Name: 'Jehanzeb Khan', Dept_Descr: 'Coporate & Direct Sales', DSG_Descr: 'Regional Head', CT_Descr: 'Karachi', TEL_EXT: '701' },
    { Emp_Name: 'Abdul Ahad Ali', Dept_Descr: 'Renewal Department', DSG_Descr: 'Collection Officer', CT_Descr: 'Karachi', TEL_EXT: '304' },
    { Emp_Name: 'Sheikh Ali Asif', Dept_Descr: 'Information Technology', DSG_Descr: 'MTO', CT_Descr: 'Karachi', TEL_EXT: '402' },
    { Emp_Name: 'Muhammad Anas', Dept_Descr: 'Human Resource', DSG_Descr: 'HR Officer', CT_Descr: 'Karachi', TEL_EXT: '404' },
    { Emp_Name: 'Muhammad Yousuf', Dept_Descr: 'Inventory & Procurement', DSG_Descr: 'Inventory Officer', CT_Descr: 'Karachi', TEL_EXT: '206' },
    { Emp_Name: 'Naheed', Dept_Descr: 'Accounts & Finance', DSG_Descr: 'Finance Officer', CT_Descr: 'Karachi', TEL_EXT: '228' },
    { Emp_Name: 'Muhammad Hamza', Dept_Descr: 'Marketing', DSG_Descr: 'Head - Marketing', CT_Descr: 'Karachi', TEL_EXT: '709' },
    { Emp_Name: 'Zaynab Mustafa', Dept_Descr: 'Renewal Department', DSG_Descr: 'Collection Officer', CT_Descr: 'Karachi', TEL_EXT: '306' },
    { Emp_Name: 'Muhammad Zubair', Dept_Descr: 'Technology Development', DSG_Descr: 'Deputy Manager, TDD', CT_Descr: 'Karachi', TEL_EXT: '705' },
    { Emp_Name: 'Muhammad Ahsan', Dept_Descr: 'Sales & Marketing', DSG_Descr: 'Sales Coordinator', CT_Descr: 'Karachi', TEL_EXT: '702' },
    { Emp_Name: 'Muhammad Rohab Saleem', Dept_Descr: 'Information Technology', DSG_Descr: 'IT Administrator', CT_Descr: 'Karachi', TEL_EXT: '401' },
    { Emp_Name: 'Aliza Waleed', Dept_Descr: 'Renewal Department', DSG_Descr: 'Collection Officer', CT_Descr: 'Karachi', TEL_EXT: '473' },
    { Emp_Name: 'Fiza Sheikh', Dept_Descr: 'Renewal Department', DSG_Descr: 'Collection Officer', CT_Descr: 'Karachi', TEL_EXT: '308' },
    { Emp_Name: 'Ahmed Farid Bokhari', Dept_Descr: 'Management', DSG_Descr: 'Director / CTO', CT_Descr: 'Karachi', TEL_EXT: '666' },
    { Emp_Name: 'Aamir Rehman Lodhi', Dept_Descr: 'Management', DSG_Descr: 'Director / COO', CT_Descr: 'Karachi', TEL_EXT: '222' },
    { Emp_Name: 'Syed Zeeshan Ahmed', Dept_Descr: 'Customer Care', DSG_Descr: 'Head – Fleet Management/Customer Care', CT_Descr: 'Karachi', TEL_EXT: '662' },
    { Emp_Name: 'Owais Akhlaq ', Dept_Descr: 'Technology Development', DSG_Descr: 'Head - Technical &Product Development', CT_Descr: 'Karachi', TEL_EXT: '800' },
    { Emp_Name: 'Muhammad Adnan', Dept_Descr: 'Inventory & Procurement', DSG_Descr: 'Executive', CT_Descr: 'Karachi', TEL_EXT: '206' },
    { Emp_Name: 'Ayaz-ul-Islam', Dept_Descr: 'Accounts & Finance', DSG_Descr: 'Executive, Accounts', CT_Descr: 'Karachi', TEL_EXT: '300' },
    { Emp_Name: 'Omar Ahmed', Dept_Descr: 'Software Development', DSG_Descr: 'Software Engineer II', CT_Descr: 'Karachi', TEL_EXT: '704' },
    { Emp_Name: 'Muhammad Zeeshan Munir', Dept_Descr: 'Software Development', DSG_Descr: 'Software Engineer I', CT_Descr: 'Karachi', TEL_EXT: '54' },
    { Emp_Name: 'Abdus Subhan', Dept_Descr: 'Software Development', DSG_Descr: 'MTO, Andriod', CT_Descr: 'Karachi', TEL_EXT: '604' },
    { Emp_Name: 'Sheraz Khalid', Dept_Descr: 'Accounts & Finance', DSG_Descr: 'Deputy Manager, Accounts & Finance', CT_Descr: 'Karachi', TEL_EXT: '303' }
  ]
}
